name: terraform-promote

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: trial-cluster    # Add your cluster name here.
  GKE_ZONE: europe-west2  # Add your cluster zone here.
  DEPLOYMENT_NAME: python-app # Add your deployment name here.
  IMAGE: python-app

jobs:
  deployment:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: Promote and Publish 
      run: |-
        sed -i -e 's/GITHUB_SHA/'"$GITHUB_SHA"'/' ${{ github.workspace }}/versions.json

        curl \
         --header "Authorization: Bearer $TERRAFORM_REGISTRY_TOKEN" \
         --header "Content-Type: application/vnd.api+json" \
         --request POST \
         --data @module.json \
        https://app.terraform.io/api/v2/organizations/$TF_ORGANIZATION/registry-modules 

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: 'v${{ github.ref_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}
